source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'





group :test do
  gem 'capybara'

end

group :development do
  gem 'guard' #by itself it doesnt do anything but has plugins  it watches file and when there is a change it will execute a task. Instead of us coding and going to writing to command line to run test it will see the save and run the test.
  gem 'guard-minitest' # the plugin to run the test 
  gem 'pry-rails'
  gem 'web-console' #the back bar in the bottom , type console and it will pop up
  gem 'guard-minitest'

end
